import { createServer, IncomingMessage, ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { access, mkdir, writeFile, unlink } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import { ZodError, z } from 'zod';
import { dataStatusSchema, documentProcessingStatusSchema, documentTypeSchema, type Component, type DataStatus, type Document, type EngineeringModule, type EngineeringValue, type Project } from '@ommatidia/shared';
import { createExtractionService } from '@ommatidia/extraction';
import { hydraulicPowerKw, toSharedCalculationResult } from '@ommatidia/calculations';
const UPLOAD_DIR = path.resolve(process.cwd(), 'storage/uploads'); const MAX_UPLOAD_SIZE_BYTES = 25 * 1024 * 1024; const ALLOWED_MIME_TYPES = new Set(['application/pdf', 'image/png', 'image/jpeg', 'image/webp']);
interface Repository<T extends { id: string }> { create(value: T): T; list(): T[]; getById(id: string): T | undefined; update(id: string, value: T): T | undefined; delete(id: string): boolean; }
class InMemoryRepository<T extends { id: string }> implements Repository<T> { private store = new Map<string, T>(); create(value: T): T { this.store.set(value.id, value); return value; } list(): T[] { return Array.from(this.store.values()); } getById(id: string): T | undefined { return this.store.get(id); } update(id: string, value: T): T | undefined { if (!this.store.has(id)) return undefined; this.store.set(id, value); return value; } delete(id: string): boolean { return this.store.delete(id); } }
const projectCreateSchema = z.object({ name: z.string(), description: z.string().optional(), projectType: z.string() });
const documentMetadataUpdateSchema = z.object({ documentType: documentTypeSchema.optional(), processingStatus: documentProcessingStatusSchema.optional(), uploadStatus: z.literal('uploaded').optional() });
const componentCreateSchema = z.object({ projectId: z.string(), name: z.string(), type: z.string(), description: z.string().optional() });
const valueCreateSchema = z.object({ projectId: z.string(), key: z.string(), label: z.string(), value: z.union([z.number(), z.string(), z.boolean(), z.array(z.record(z.any())), z.array(z.any())]), valueType: z.enum(['number', 'string', 'boolean', 'table', 'list']), unit: z.string().optional(), status: dataStatusSchema, sourceReferences: z.array(z.any()), componentId: z.string().optional(), documentId: z.string().optional() });
const moduleCreateSchema = z.object({ name: z.string(), description: z.string(), moduleType: z.enum(['extraction','summary','comparison','calculation','checklist','report']), applicableProjectTypes: z.array(z.string()), inputs: z.array(z.any()), outputs: z.array(z.any()) });
const valueStatusUpdateSchema = z.object({ status: dataStatusSchema }); const extractionStartSchema = z.object({ projectId: z.string(), documentId: z.string(), extractionTarget: z.object({ componentType: z.string().optional(), moduleType: z.string().optional() }).optional() }); const calcSchema = z.object({ projectId: z.string(), flowLpm: z.number(), pressureBar: z.number(), efficiency: z.number() });
function readBody(req: IncomingMessage): Promise<unknown> { return new Promise((resolve, reject) => { let data = ''; req.on('data', (chunk) => data += chunk); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('Invalid JSON body')); } }); req.on('error', reject); }); }
function readRawBody(req: IncomingMessage): Promise<Buffer> { return new Promise((resolve,reject)=>{ const chunks: Buffer[]=[]; let total=0; req.on('data',(chunk:Buffer)=>{ total += chunk.length; if (total > MAX_UPLOAD_SIZE_BYTES) { reject(new Error(`File exceeds max size of ${MAX_UPLOAD_SIZE_BYTES} bytes`)); req.destroy(); return;} chunks.push(chunk);}); req.on('end',()=>resolve(Buffer.concat(chunks))); req.on('error',reject); }); }
function sendJson(res: ServerResponse, status: number, body: unknown): void { res.statusCode=status; res.setHeader('content-type','application/json'); res.end(JSON.stringify(body)); }
function parseId(pathname:string){ return pathname.split('/')[3]; }
export function createApiHandler(){ const projects=new InMemoryRepository<Project>(); const documents=new InMemoryRepository<Document>(); const components=new InMemoryRepository<Component>(); const values=new InMemoryRepository<EngineeringValue>(); const modules=new InMemoryRepository<EngineeringModule>(); const extractionService = createExtractionService();
return async function handler(req: IncomingMessage, res: ServerResponse){ const method=req.method??'GET'; const url=new URL(req.url??'/', 'http://localhost'); const {pathname,searchParams}=url; try {
if(method==='POST'&&pathname==='/projects') return sendJson(res,201,projects.create({...projectCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));
if(method==='GET'&&pathname==='/projects') return sendJson(res,200,projects.list());
if(method==='POST'&&/^\/projects\/[^/]+\/documents$/.test(pathname)){ const projectId=pathname.split('/')[2]; if(!projects.getById(projectId)) return sendJson(res,404,{error:'Project not found'}); const mimeType=String(req.headers['content-type']||''); if(!ALLOWED_MIME_TYPES.has(mimeType)) return sendJson(res,400,{error:'Unsupported file type. Allowed: pdf, png, jpg, jpeg, webp.'}); const documentType=documentTypeSchema.parse(String(req.headers['x-document-type']||'')); const originalFilename=path.basename(String(req.headers['x-filename']||'upload')); const ext = mimeType==='application/pdf'?'.pdf':mimeType==='image/png'?'.png':mimeType==='image/webp'?'.webp':'.jpg'; const storedFilename=`${Date.now()}-${randomUUID()}${ext}`; await mkdir(UPLOAD_DIR,{recursive:true}); const raw=await readRawBody(req); const storedPath=path.join(UPLOAD_DIR,storedFilename); await writeFile(storedPath,raw); const now=new Date().toISOString(); return sendJson(res,201,documents.create({id:randomUUID(),projectId,originalFilename,storedFilename,mimeType,fileSizeBytes:raw.length,documentType,uploadStatus:'uploaded',processingStatus:'uploaded',createdAt:now,updatedAt:now})); }
if(method==='GET'&&pathname==='/documents'){ const projectId=searchParams.get('projectId'); return sendJson(res,200,projectId?documents.list().filter(d=>d.projectId===projectId):documents.list()); }
if(pathname.startsWith('/documents/')){ const id=parseId(pathname); const existing=id?documents.getById(id):undefined; if(!existing) return sendJson(res,404,{error:'Document not found'}); if(method==='GET') return sendJson(res,200,existing); if(method==='PUT') return sendJson(res,200,documents.update(id,{...existing,...documentMetadataUpdateSchema.parse(await readBody(req)),updatedAt:new Date().toISOString()} as Document)); if(method==='DELETE'){ documents.delete(id); await unlink(path.join(UPLOAD_DIR,existing.storedFilename)).catch(()=>undefined); return sendJson(res,200,{deleted:true}); }}
if(method==='GET'&&/^\/documents\/[^/]+\/file$/.test(pathname)){ const id=pathname.split('/')[2]; const existing=documents.getById(id); if(!existing) return sendJson(res,404,{error:'Document not found'}); res.statusCode=200; res.setHeader('content-type',existing.mimeType); return createReadStream(path.join(UPLOAD_DIR,path.basename(existing.storedFilename))).pipe(res); }
if(method==='POST'&&pathname==='/components') return sendJson(res,201,components.create({...componentCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));
if(method==='GET'&&pathname==='/components'){ const projectId=searchParams.get('projectId'); return sendJson(res,200,projectId?components.list().filter(c=>c.projectId===projectId):components.list()); }

if(method==='GET'&&pathname==='/engineering-values'){ const projectId=searchParams.get('projectId'); return sendJson(res,200,projectId?values.list().filter(v=>v.projectId===projectId):values.list()); }
if(method==='POST'&&pathname==='/extractions'){ const body=extractionStartSchema.parse(await readBody(req)); const doc=documents.getById(body.documentId); if(!doc||doc.projectId!==body.projectId) return sendJson(res,404,{error:'Document not found'}); const filePath=path.join(UPLOAD_DIR,path.basename(doc.storedFilename)); try { await mkdir(UPLOAD_DIR,{recursive:true}); await access(filePath); } catch { return sendJson(res,400,{error:'Document file is missing on disk'}); }
const result = await extractionService.extractEngineeringValues({ projectId: body.projectId, documentId: body.documentId, document: doc, documentFilePath: filePath, extractionTarget: body.extractionTarget });
for(const candidate of result.candidateValues){ const existingApproved=values.list().find(v=>v.projectId===candidate.projectId&&v.key===candidate.key&&v.componentId===candidate.componentId&&v.status==='approved'); if(existingApproved) continue; values.create(candidate as EngineeringValue); }
return sendJson(res,200,result);
}
if(method==='POST'&&pathname==='/engineering-values') return sendJson(res,201,values.create({...valueCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} as EngineeringValue));
if(method==='PATCH'&&/^\/engineering-values\/[^/]+\/status$/.test(pathname)){ const id=pathname.split('/')[2]; const existing=values.getById(id); if(!existing) return sendJson(res,404,{error:'Engineering value not found'}); return sendJson(res,200,values.update(id,{...existing,status:valueStatusUpdateSchema.parse(await readBody(req)).status as DataStatus,updatedAt:new Date().toISOString()})); }
if(method==='POST'&&pathname==='/engineering-modules') return sendJson(res,201,modules.create({...moduleCreateSchema.parse(await readBody(req)),id:randomUUID()} as EngineeringModule));
if(method==='GET'&&pathname==='/engineering-modules') return sendJson(res,200,modules.list());
if(method==='POST'&&pathname==='/calculations/hydraulic-power-kw'){ const input=calcSchema.parse(await readBody(req)); return sendJson(res,200,toSharedCalculationResult('hydraulicPowerKw',input.projectId,'hydraulic_power_kw','Hydraulic power',hydraulicPowerKw(input.flowLpm,input.pressureBar,input.efficiency))); }
return sendJson(res,404,{error:'Not found'});
} catch(error){ if(error instanceof ZodError) return sendJson(res,400,{error:'Validation failed',details:error.issues}); if(error instanceof Error) return sendJson(res,400,{error:error.message}); return sendJson(res,500,{error:'Unknown error'}); }}; }
export function startApiServer(port=3000){ const server=createServer(createApiHandler()); server.listen(port); return server; }
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href){ startApiServer(); }
