import { createServer, IncomingMessage, ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { access, mkdir, writeFile, unlink } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import { ZodError, z } from 'zod';
import { dataStatusSchema, documentProcessingStatusSchema, documentTypeSchema, reportSectionSchema, type CalculationResult, type Component, type DataStatus, type Document, type EngineeringModule, type EngineeringValue, type Project, type ReportSection, type SourceReference, type ComponentLibraryItem, componentLibraryItemSchema, sourceReferenceSchema } from '@ommatidia/shared';
import { createExtractionService, getDefaultOpenAiExtractionModel, runOpenAiSmokeTest, type ExtractionErrorCode, ExtractionError, normalizedExtractionError } from '@ommatidia/extraction';
import { RuntimeSettingsService } from './runtimeSettings.js';
import { hydraulicPowerKw, toSharedCalculationResult } from '@ommatidia/calculations';
import { exportReportSectionsToDocx, generateReportSection, type ReportGenerationInput, type ReportSectionType } from '@ommatidia/reports';
const UPLOAD_DIR = path.resolve(process.cwd(), 'storage/uploads'); const MAX_UPLOAD_SIZE_BYTES = 25 * 1024 * 1024; const ALLOWED_MIME_TYPES = new Set(['application/pdf', 'image/png', 'image/jpeg', 'image/webp']);
interface Repository<T extends { id: string }> { create(value: T): T; list(): T[]; getById(id: string): T | undefined; update(id: string, value: T): T | undefined; delete(id: string): boolean; }
class InMemoryRepository<T extends { id: string }> implements Repository<T> { private store = new Map<string, T>(); create(value: T): T { this.store.set(value.id, value); return value; } list(): T[] { return Array.from(this.store.values()); } getById(id: string): T | undefined { return this.store.get(id); } update(id: string, value: T): T | undefined { if (!this.store.has(id)) return undefined; this.store.set(id, value); return value; } delete(id: string): boolean { return this.store.delete(id); } }
interface ExtractionAttempt { id: string; projectId: string; documentId: string; provider: string; status: 'pending'|'succeeded'|'failed'; startedAt: string; completedAt?: string; errorCode?: ExtractionErrorCode; safeErrorMessage?: string; valuesCreatedCount: number; createdCandidateKeys?: string[]; warnings: string[]; diagnostics?: Record<string, unknown>; }
interface ExtractionFixture { id: string; name: string; originalFilename: string; documentType: string; componentType?: string; componentName?: string; candidateValues: EngineeringValue[]; warnings: string[]; createdAt: string; }
const projectCreateSchema = z.object({ name: z.string(), description: z.string().optional(), projectType: z.string() });
const documentMetadataUpdateSchema = z.object({ documentType: documentTypeSchema.optional(), processingStatus: documentProcessingStatusSchema.optional(), uploadStatus: z.literal('uploaded').optional(), componentId: z.string().optional() });
const componentCreateSchema = z.object({ projectId: z.string(), name: z.string(), type: z.string(), description: z.string().optional() });
const valueCreateSchema = z.object({ projectId: z.string(), key: z.string(), label: z.string(), value: z.union([z.number(), z.string(), z.boolean(), z.array(z.record(z.any())), z.array(z.any())]), valueType: z.enum(['number', 'string', 'boolean', 'table', 'list']), unit: z.string().optional(), status: dataStatusSchema, sourceReferences: z.array(z.any()), componentId: z.string().optional(), documentId: z.string().optional() });
const moduleCreateSchema = z.object({ name: z.string(), description: z.string(), moduleType: z.enum(['extraction','summary','comparison','calculation','checklist','report']), applicableProjectTypes: z.array(z.string()), inputs: z.array(z.any()), outputs: z.array(z.any()) });
const valueStatusUpdateSchema = z.object({ status: dataStatusSchema });
const componentLibraryPromoteSchema = z.object({ projectId: z.string(), componentId: z.string(), name: z.string().optional(), tags: z.array(z.string()).optional(), description: z.string().optional() });
const copyLibrarySchema = z.object({ targetProjectId: z.string(), componentName: z.string().optional() });
const compareLibrarySchema = z.object({ targetProjectId: z.string(), targetComponentId: z.string() });

const reportGenerationSchema = z.object({ projectId: z.string(), componentId: z.string().optional(), sectionType: z.enum(['component_summary','calculation_summary','assumptions_and_warnings','missing_information','source_references']), engineeringValues: z.array(z.any()), calculationResults: z.array(z.any()).optional(), missingInformation: z.array(z.string()).optional(), assumptions: z.array(z.string()).optional(), warnings: z.array(z.string()).optional(), sourceReferences: z.array(z.any()).optional() });
const reportSectionUpdateSchema = z.object({ title: z.string().optional(), bodyMarkdown: z.string().optional(), status: dataStatusSchema.optional() });
const reportDocxExportSchema = z.object({ projectId: z.string(), reportSectionIds: z.array(z.string()), documentTitle: z.string().optional(), generatedBy: z.string().optional(), generatedAt: z.string().optional(), includeSourceReferences: z.boolean().optional() });
const extractionStartSchema = z.object({ projectId: z.string(), documentId: z.string(), componentId: z.string().optional(), fixtureId: z.string().optional(), extractionTarget: z.object({ componentType: z.string().optional(), moduleType: z.string().optional() }).optional() }); const calcSchema = z.object({ projectId: z.string(), flowLpm: z.number(), pressureBar: z.number(), efficiency: z.number() });
const extractionProviderUpdateSchema = z.object({ extractionProvider: z.enum(['mock', 'fixture', 'openai']) });
const openAiKeyUpdateSchema = z.object({ apiKey: z.string() });

const extractionFixtureCreateSchema = z.object({
  name: z.string(),
  originalFilename: z.string(),
  documentType: z.string(),
  componentType: z.string().optional(),
  componentName: z.string().optional(),
  candidateValues: z.array(z.any()),
  warnings: z.array(z.string())
});
function sanitizeFixtureValue(input: unknown): unknown {
  if (Array.isArray(input)) return input.map(sanitizeFixtureValue);
  if (input && typeof input === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(input as Record<string, unknown>)) {
      if (/(api[_-]?key|token|authorization|secret)/i.test(k)) continue;
      if (k === 'rawText' || k === 'rawDocumentText' || k === 'documentText') continue;
      out[k] = sanitizeFixtureValue(v);
    }
    return out;
  }
  return input;
}

function readBody(req: IncomingMessage): Promise<unknown> { return new Promise((resolve, reject) => { let data = ''; req.on('data', (chunk) => data += chunk); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('Invalid JSON body')); } }); req.on('error', reject); }); }
function readRawBody(req: IncomingMessage): Promise<Buffer> { return new Promise((resolve,reject)=>{ const chunks: Buffer[]=[]; let total=0; req.on('data',(chunk:Buffer)=>{ total += chunk.length; if (total > MAX_UPLOAD_SIZE_BYTES) { reject(new Error(`File exceeds max size of ${MAX_UPLOAD_SIZE_BYTES} bytes`)); req.destroy(); return;} chunks.push(chunk);}); req.on('end',()=>resolve(Buffer.concat(chunks))); req.on('error',reject); }); }
function getAllowedOrigin(origin: string | undefined): string | undefined {
  if (!origin) return undefined;
  if (/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(origin)) return origin;
  if (/^https:\/\/[a-z0-9-]+-\d+\.app\.github\.dev$/i.test(origin)) return origin;
  return undefined;
}
function applyCorsHeaders(req: IncomingMessage, res: ServerResponse): void {
  const allowedOrigin = getAllowedOrigin(typeof req.headers.origin === 'string' ? req.headers.origin : undefined);
  if (allowedOrigin) res.setHeader('access-control-allow-origin', allowedOrigin);
  res.setHeader('access-control-allow-methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
  res.setHeader('access-control-allow-headers', 'content-type,x-document-type,x-filename');
  res.setHeader('vary', 'Origin');
}
function sendJson(req: IncomingMessage, res: ServerResponse, status: number, body: unknown): void { applyCorsHeaders(req, res); res.statusCode=status; res.setHeader('content-type','application/json'); res.end(JSON.stringify(body)); }
const errorStatusMap: Record<ExtractionErrorCode, number> = { missing_api_key: 401, invalid_api_key: 401, permission_denied: 403, provider_unavailable: 503, request_timeout: 408, rate_limited: 429, model_not_found: 400, bad_request: 400, network_failure: 503, invalid_model_response: 400, invalid_json_response: 400, schema_invalid_response: 400, unsupported_response_shape: 400, no_document_content: 400, file_not_found: 404, unsupported_file_type: 400, file_too_large: 400, extraction_failed: 500, unknown_error: 500 };
function resolveExtractionProvider(): 'openai' | 'mock' | 'fixture' | 'unknown' { const provider = (process.env.EXTRACTION_PROVIDER ?? 'mock').trim().toLowerCase(); if (provider === 'openai' || provider === 'mock' || provider === 'fixture') return provider; return 'unknown'; }
async function createSafeSystemStatus(settings: RuntimeSettingsService, extractionProvider: 'mock' | 'fixture' | 'openai') { const safe = await settings.getSafeStatus(extractionProvider, getDefaultOpenAiExtractionModel()); return { ok: true, extractionProvider, openAiConfigured: safe.openAiConfigured, openAiKeySource: safe.openAiKeySource, openAiModel: safe.openAiModel, extractionConfig: { timeoutMs: Number(process.env.EXTRACTION_TIMEOUT_MS ?? 120000), maxRetries: Number(process.env.EXTRACTION_MAX_RETRIES ?? 1) }, apiProxyMode: true, timestamp: new Date().toISOString() }; }

export function createApiHandler(){ const projects=new InMemoryRepository<Project>(); const documents=new InMemoryRepository<Document>(); const components=new InMemoryRepository<Component>(); const values=new InMemoryRepository<EngineeringValue>(); const modules=new InMemoryRepository<EngineeringModule>(); const attempts = new InMemoryRepository<ExtractionAttempt>(); const reportSections = new InMemoryRepository<ReportSection>(); const componentLibrary = new InMemoryRepository<ComponentLibraryItem>(); const calculationResults: CalculationResult[] = []; let extractionProvider: 'mock' | 'fixture' | 'openai' = resolveExtractionProvider() === 'openai' ? 'openai' : (resolveExtractionProvider() === 'fixture' ? 'fixture' : 'mock');
const fixtures = new InMemoryRepository<ExtractionFixture>();
const runtimeSettings = new RuntimeSettingsService();
const withEffectiveOpenAiKey = async <T>(fn: () => Promise<T>): Promise<T> => { const previous = process.env.OPENAI_API_KEY; const effective = await runtimeSettings.getEffectiveOpenAiKey(); if (effective) process.env.OPENAI_API_KEY = effective; else delete process.env.OPENAI_API_KEY; try { return await fn(); } finally { if (previous === undefined) delete process.env.OPENAI_API_KEY; else process.env.OPENAI_API_KEY = previous; } };
const getExtractionService = () => createExtractionService(extractionProvider === 'fixture' ? 'mock' : extractionProvider);
return async function handler(req: IncomingMessage, res: ServerResponse){ const method=req.method??'GET'; const url=new URL(req.url??'/', 'http://localhost'); const {pathname,searchParams}=url; try {
if(method==='OPTIONS'){ applyCorsHeaders(req, res); res.statusCode = 204; res.end(); return; }
if(method==='POST'&&pathname==='/projects') return sendJson(req, res,201,projects.create({...projectCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));
if(method==='GET'&&pathname==='/projects') return sendJson(req, res,200,projects.list());
if(method==='GET'&&pathname==='/system/status') return sendJson(req, res,200,await createSafeSystemStatus(runtimeSettings, extractionProvider));
if(method==='GET'&&pathname==='/system/settings') return sendJson(req,res,200,await runtimeSettings.getSafeStatus(extractionProvider,getDefaultOpenAiExtractionModel()));
if(method==='PATCH'&&pathname==='/system/settings/openai-key'){ const { apiKey } = openAiKeyUpdateSchema.parse(await readBody(req)); await runtimeSettings.setOpenAiKey(apiKey); return sendJson(req,res,200,await runtimeSettings.getSafeStatus(extractionProvider,getDefaultOpenAiExtractionModel())); }
if(method==='DELETE'&&pathname==='/system/settings/openai-key'){ await runtimeSettings.clearOpenAiKey(); return sendJson(req,res,200,await runtimeSettings.getSafeStatus(extractionProvider,getDefaultOpenAiExtractionModel())); }
if(method==='GET'&&pathname==='/system/openai-smoke-test'){ const result = await withEffectiveOpenAiKey(() => runOpenAiSmokeTest()); return sendJson(req,res,result.ok?200:502,result); }
if(method==='PATCH'&&pathname==='/system/extraction-provider'){ const { extractionProvider: requestedProvider } = extractionProviderUpdateSchema.parse(await readBody(req)); const source = await runtimeSettings.getOpenAiKeySource(); if(requestedProvider==='openai'&&source==='none') return sendJson(req,res,400,{ message:'OpenAI API key is not configured on the server.' }); extractionProvider=requestedProvider; return sendJson(req,res,200,await createSafeSystemStatus(runtimeSettings, extractionProvider)); }

if(method==='GET'&&/^\/projects\/[^/]+$/.test(pathname)){ const id=pathname.split('/')[2]; const project=projects.getById(id); if(!project) return sendJson(req, res,404,{error:'Project not found'}); return sendJson(req, res,200,project); }

if(method==='POST'&&/^\/projects\/[^/]+\/documents$/.test(pathname)){ const projectId=pathname.split('/')[2]; if(!projects.getById(projectId)) return sendJson(req, res,404,{error:'Project not found'}); const mimeType=String(req.headers['content-type']||''); if(!ALLOWED_MIME_TYPES.has(mimeType)) return sendJson(req, res,400,normalizedExtractionError('unsupported_file_type','Unsupported file type.',false)); const documentType=documentTypeSchema.parse(String(req.headers['x-document-type']||'')); const originalFilename=path.basename(String(req.headers['x-filename']||'upload')); const ext = mimeType==='application/pdf'?'.pdf':mimeType==='image/png'?'.png':mimeType==='image/webp'?'.webp':'.jpg'; const storedFilename=`${Date.now()}-${randomUUID()}${ext}`; await mkdir(UPLOAD_DIR,{recursive:true}); const raw=await readRawBody(req); const storedPath=path.join(UPLOAD_DIR,storedFilename); await writeFile(storedPath,raw); const now=new Date().toISOString(); return sendJson(req, res,201,documents.create({id:randomUUID(),projectId,originalFilename,storedFilename,mimeType,fileSizeBytes:raw.length,documentType,uploadStatus:'uploaded',processingStatus:'uploaded',componentId:undefined,createdAt:now,updatedAt:now})); }
if(method==='GET'&&pathname==='/documents'){ const projectId=searchParams.get('projectId'); return sendJson(req, res,200,projectId?documents.list().filter(d=>d.projectId===projectId):documents.list()); }
if(method==='GET'&&pathname==='/extractions/attempts'){ const projectId=String(searchParams.get('projectId') ?? ''); const documentId=String(searchParams.get('documentId') ?? ''); return sendJson(req, res,200,attempts.list().filter((a)=>a.projectId===projectId&&a.documentId===documentId)); }

if(method==='POST'&&pathname==='/extraction-fixtures'){
  const payload = extractionFixtureCreateSchema.parse(await readBody(req));
  const now = new Date().toISOString();
  const normalizedCandidates = payload.candidateValues.map((candidate) => sanitizeFixtureValue(candidate)) as EngineeringValue[];
  const fixture = fixtures.create({ id: randomUUID(), name: payload.name, originalFilename: payload.originalFilename, documentType: payload.documentType, componentType: payload.componentType, componentName: payload.componentName, candidateValues: normalizedCandidates, warnings: payload.warnings, createdAt: now });
  return sendJson(req,res,201,{ fixtureId: fixture.id, ...fixture });
}
if(method==='GET'&&pathname==='/extraction-fixtures') return sendJson(req,res,200,fixtures.list().map((f)=>({ fixtureId:f.id, ...f })));
if(method==='GET'&&/^\/extraction-fixtures\/[^/]+$/.test(pathname)){ const fixtureId=pathname.split('/')[2]; const fixture=fixtures.getById(fixtureId); if(!fixture) return sendJson(req,res,404,{error:'Fixture not found'}); return sendJson(req,res,200,{ fixtureId: fixture.id, ...fixture }); }
if(method==='DELETE'&&/^\/extraction-fixtures\/[^/]+$/.test(pathname)){ const fixtureId=pathname.split('/')[2]; return sendJson(req,res,200,{ deleted: fixtures.delete(fixtureId) }); }

if(pathname.startsWith('/documents/')){ const id=pathname.split('/')[2]; const existing=id?documents.getById(id):undefined; if(!existing) return sendJson(req, res,404,{error:'Document not found'}); if(method==='GET') return sendJson(req, res,200,existing); if(method==='PUT') return sendJson(req, res,200,documents.update(id,{...existing,...documentMetadataUpdateSchema.parse(await readBody(req)),updatedAt:new Date().toISOString()} as Document)); if(method==='DELETE'){ documents.delete(id); await unlink(path.join(UPLOAD_DIR,existing.storedFilename)).catch(()=>undefined); return sendJson(req, res,200,{deleted:true}); }}

if(method==='GET'&&/^\/documents\/[^/]+\/extracted-text-preview$/.test(pathname)){ const id=pathname.split('/')[2]; const doc=documents.getById(id); if(!doc) return sendJson(req,res,404,{error:'Document not found'}); const filePath=path.join(UPLOAD_DIR,path.basename(doc.storedFilename)); try { await access(filePath); } catch { return sendJson(req,res,404,normalizedExtractionError('file_not_found','Document file is missing.',false)); }
  const result = await withEffectiveOpenAiKey(() => getExtractionService().extractEngineeringValues({ projectId: doc.projectId, documentId: doc.id, document: doc, documentFilePath: filePath }));
  const pdf = (result.diagnostics?.pdfTextExtraction ?? {}) as Record<string, unknown>;
  return sendJson(req,res,200,{ documentId: doc.id, originalFilename: doc.originalFilename, extracted: Number(pdf.extractedCharacterCount ?? 0) > 0, chars: Number(pdf.extractedCharacterCount ?? 0), usefulChars: Number(pdf.usefulTextCharacterCount ?? 0), suspiciousRatio: Number(pdf.suspiciousInternalTextRatio ?? 0), preview: typeof result.diagnostics?.pdfTextPreview==='string'?result.diagnostics.pdfTextPreview:'', warnings: result.warnings ?? [] });
}

if(method==='GET'&&/^\/documents\/[^/]+\/file$/.test(pathname)){ const id=pathname.split('/')[2]; const existing=documents.getById(id); if(!existing) return sendJson(req, res,404,{error:'Document not found'}); res.statusCode=200; res.setHeader('content-type',existing.mimeType); return createReadStream(path.join(UPLOAD_DIR,path.basename(existing.storedFilename))).pipe(res); }
if(method==='POST'&&pathname==='/components') return sendJson(req, res,201,components.create({...componentCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));
if(method==='GET'&&pathname==='/components'){ const projectId=searchParams.get('projectId'); return sendJson(req, res,200,projectId?components.list().filter(c=>c.projectId===projectId):components.list()); }
if(method==='GET'&&pathname==='/engineering-values'){ const projectId=searchParams.get('projectId'); return sendJson(req, res,200,projectId?values.list().filter(v=>v.projectId===projectId):values.list()); }
if(method==='POST'&&pathname==='/extractions'){ const body=extractionStartSchema.parse(await readBody(req)); const doc=documents.getById(body.documentId); if(!doc||doc.projectId!==body.projectId) return sendJson(req, res,404,normalizedExtractionError('file_not_found','Document not found.',false)); const filePath=path.join(UPLOAD_DIR,path.basename(doc.storedFilename)); try { await mkdir(UPLOAD_DIR,{recursive:true}); await access(filePath); } catch { return sendJson(req, res,404,normalizedExtractionError('file_not_found','Document file is missing.',false)); }
const attempt: ExtractionAttempt = { id: randomUUID(), projectId: body.projectId, documentId: body.documentId, provider: extractionProvider, status: 'pending', startedAt: new Date().toISOString(), valuesCreatedCount: 0, warnings: [] }; attempts.create(attempt);
try { const selectedComponentId = body.componentId ?? doc.componentId; const selectedComponent = selectedComponentId ? components.getById(selectedComponentId) : undefined; const extractionTarget = { ...(body.extractionTarget ?? {}), componentType: selectedComponent?.type ?? body.extractionTarget?.componentType }; const result = extractionProvider === 'fixture'
? (() => {
  const fixture = fixtures.getById(body.fixtureId ?? '');
  if (!fixture) throw new ExtractionError(normalizedExtractionError('bad_request', 'Fixture provider requires a valid fixtureId.', false));
  const now = new Date().toISOString();
  const candidateValues = fixture.candidateValues.map((c) => ({ ...c, id: randomUUID(), projectId: body.projectId, documentId: body.documentId, componentId: selectedComponentId, status: 'needs_review', createdAt: now, updatedAt: now })) as EngineeringValue[];
  return { candidateValues, missingInformation: [], warnings: [`Fixture replayed: ${fixture.name}. This is test data and does not call OpenAI.`], providerMetadata: { provider: 'fixture' as const }, diagnostics: { fixtureId: fixture.id, fixtureName: fixture.name, fixtureReplay: true, contentSentToModel: false, openAiCalled: false } };
})()
: await withEffectiveOpenAiKey(() => getExtractionService().extractEngineeringValues({ projectId: body.projectId, documentId: body.documentId, componentId: selectedComponentId, document: doc, documentFilePath: filePath, extractionTarget }));
let skippedApprovedConflictCount = 0;
const createdCandidateKeys: string[] = [];
for(const candidate of result.candidateValues){ const normalizedCandidate = { ...candidate, componentId: selectedComponentId ?? candidate.componentId } as EngineeringValue; const existingApproved=values.list().find(v=>v.projectId===normalizedCandidate.projectId&&v.key===normalizedCandidate.key&&v.componentId===normalizedCandidate.componentId&&v.status==='approved'); if(existingApproved){ skippedApprovedConflictCount += 1; continue; } const saved = values.create(normalizedCandidate); attempt.valuesCreatedCount += 1; createdCandidateKeys.push(saved.key); }
attempt.createdCandidateKeys = createdCandidateKeys;
attempt.warnings = [...result.warnings];
if (attempt.valuesCreatedCount === 0 && !attempt.warnings.some((w) => w.toLowerCase().includes('no engineering values'))) attempt.warnings.push('No engineering values were extracted from this document.');
if (skippedApprovedConflictCount > 0) attempt.warnings.push(`Skipped ${skippedApprovedConflictCount} candidate value(s) because approved values already exist.`);
attempt.diagnostics = { ...(result.diagnostics ?? {}), skippedApprovedConflictCount, createdCandidateKeys, ...(extractionProvider === 'fixture' ? { fixtureId: body.fixtureId } : {}) };
attempt.status='succeeded'; attempt.completedAt=new Date().toISOString(); attempts.update(attempt.id, attempt); return sendJson(req, res,200,{...result, warnings: attempt.warnings, valuesCreatedCount: attempt.valuesCreatedCount, createdCandidateKeys, diagnostics: attempt.diagnostics}); } catch (error) { const payload = error instanceof ExtractionError ? error.payload : normalizedExtractionError('unknown_error','Extraction failed.',false); attempt.status='failed'; attempt.completedAt=new Date().toISOString(); attempt.errorCode=payload.errorCode; attempt.safeErrorMessage=payload.message; attempts.update(attempt.id, attempt); console.error(JSON.stringify({ event: 'extraction_failed', errorCode: payload.errorCode, provider: attempt.provider, model: payload.details?.model, statusCode: payload.details?.statusCode, safeProviderMessage: payload.details?.safeProviderMessage, retryable: payload.retryable, projectId: attempt.projectId, documentId: attempt.documentId, attemptId: attempt.id, timestamp: payload.timestamp })); return sendJson(req, res, errorStatusMap[payload.errorCode] ?? 500, payload); }
}
if(method==='POST'&&pathname==='/engineering-values') return sendJson(req, res,201,values.create({...valueCreateSchema.parse(await readBody(req)),id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} as EngineeringValue));
if(method==='PATCH'&&/^\/engineering-values\/[^/]+$/.test(pathname)){ const id=pathname.split('/')[2]; const existing=values.getById(id); if(!existing) return sendJson(req, res,404,{error:'Engineering value not found'}); const body = await readBody(req) as Record<string, unknown>; const next = { ...existing, ...(typeof body.componentId === 'string' ? { componentId: body.componentId } : {}), updatedAt:new Date().toISOString() }; return sendJson(req,res,200,values.update(id,next as EngineeringValue)); }
if(method==='PATCH'&&/^\/engineering-values\/[^/]+\/status$/.test(pathname)){ const id=pathname.split('/')[2]; const existing=values.getById(id); if(!existing) return sendJson(req, res,404,{error:'Engineering value not found'}); return sendJson(req, res,200,values.update(id,{...existing,status:valueStatusUpdateSchema.parse(await readBody(req)).status as DataStatus,updatedAt:new Date().toISOString()})); }
if(method==='POST'&&pathname==='/engineering-modules') return sendJson(req, res,201,modules.create({...moduleCreateSchema.parse(await readBody(req)),id:randomUUID()} as EngineeringModule));
if(method==='GET'&&pathname==='/engineering-modules') return sendJson(req, res,200,modules.list());
if(method==='POST'&&pathname==='/calculations/hydraulic-power-kw'){ const input=calcSchema.parse(await readBody(req)); const result = toSharedCalculationResult('hydraulicPowerKw',input.projectId,'hydraulic_power_kw','Hydraulic power',hydraulicPowerKw(input.flowLpm,input.pressureBar,input.efficiency)); calculationResults.push(result as unknown as CalculationResult); return sendJson(req, res,200,result); }

if(method==='POST'&&pathname==='/component-library/promote'){ const input=componentLibraryPromoteSchema.parse(await readBody(req)); const component=components.getById(input.componentId); if(!component||component.projectId!==input.projectId) return sendJson(req, res,404,{error:'Component not found'}); const sourceValues=values.list().filter((v)=>v.projectId===input.projectId&&v.componentId===input.componentId); const eligible=sourceValues.filter((v)=>v.status==='approved'||v.status==='user_entered').map((v)=>({key:v.key,label:v.label,value:v.value,valueType:v.valueType,unit:v.unit,status:v.status,sourceReferences:v.sourceReferences,notes:v.notes})); if(eligible.length===0) return sendJson(req, res,400,{error:'No eligible approved or user_entered engineering values found for promotion'}); const refs=sourceValues.flatMap((v)=>v.sourceReferences).map((r)=>sourceReferenceSchema.parse(r)); const now=new Date().toISOString(); const normalizedTags=(input.tags ?? []).map((tag)=>tag.trim()).filter(Boolean); const item=componentLibrary.create(componentLibraryItemSchema.parse({ id:randomUUID(), name:input.name ?? component.name, componentType:component.type, description:input.description ?? component.description, approvedEngineeringValues:eligible, sourceReferences:refs, originatingProjectId:input.projectId, originatingComponentId:input.componentId, tags:normalizedTags, createdAt:now, updatedAt:now })); return sendJson(req, res,201,item); }
if(method==='GET'&&pathname==='/component-library'){ const q=(searchParams.get('q') ?? '').toLowerCase(); const rows=componentLibrary.list().filter((row)=>!q || row.name.toLowerCase().includes(q) || row.componentType.toLowerCase().includes(q) || row.tags.some((t: string)=>t.toLowerCase().includes(q)) || row.approvedEngineeringValues.some((v)=>['manufacturer','model'].includes(v.key.toLowerCase()) && String(v.value).toLowerCase().includes(q))); return sendJson(req, res,200,rows); }
if(method==='GET'&&/^\/component-library\/[^/]+$/.test(pathname)){ const id=pathname.split('/')[2]; const item=componentLibrary.getById(id); if(!item) return sendJson(req, res,404,{error:'Library component not found'}); return sendJson(req, res,200,item); }
if(method==='POST'&&/^\/component-library\/[^/]+\/copy-to-project$/.test(pathname)){ const id=pathname.split('/')[2]; const item=componentLibrary.getById(id); if(!item) return sendJson(req, res,404,{error:'Library component not found'}); const input=copyLibrarySchema.parse(await readBody(req)); const project=projects.getById(input.targetProjectId); if(!project) return sendJson(req, res,404,{error:'Target project not found'}); const now=new Date().toISOString(); const newComponent=components.create({ id:randomUUID(), projectId:input.targetProjectId, name:input.componentName ?? item.name, type:item.componentType, description:item.description, createdAt:now, updatedAt:now }); const createdValues=item.approvedEngineeringValues.map((v: ComponentLibraryItem['approvedEngineeringValues'][number])=>values.create({ id:randomUUID(), projectId:input.targetProjectId, componentId:newComponent.id, key:v.key, label:v.label, value:v.value, valueType:v.valueType, unit:v.unit, status:v.status==='approved'?'approved':'user_entered', sourceReferences:v.sourceReferences, notes:[v.notes, `Copied from library component ${item.name} (${item.id})`].filter(Boolean).join(' | '), createdAt:now, updatedAt:now } as EngineeringValue)); return sendJson(req, res,201,{component:newComponent, engineeringValues:createdValues}); }
if(method==='POST'&&/^\/component-library\/[^/]+\/compare$/.test(pathname)){ const id=pathname.split('/')[2]; const item=componentLibrary.getById(id); if(!item) return sendJson(req, res,404,{error:'Library component not found'}); const input=compareLibrarySchema.parse(await readBody(req)); const target=components.getById(input.targetComponentId); if(!target||target.projectId!==input.targetProjectId) return sendJson(req, res,404,{error:'Target component not found'}); const targetValues=values.list().filter((v)=>v.projectId===input.targetProjectId&&v.componentId===input.targetComponentId); const byKey=new Map(targetValues.map((v)=>[v.key,v])); const matching=[] as unknown[]; const differing=[] as unknown[]; const missingInTarget=[] as unknown[]; for(const lv of item.approvedEngineeringValues){ const tv=byKey.get(lv.key); if(!tv){ missingInTarget.push(lv); continue; } byKey.delete(lv.key); if(tv.value===lv.value && (tv.unit??null)===(lv.unit??null)){ matching.push({key:lv.key,library:lv,target:tv}); } else { differing.push({key:lv.key,library:{value:lv.value,unit:lv.unit},target:{value:tv.value,unit:tv.unit}}); } } const extraInTarget=Array.from(byKey.values()).map((v)=>({key:v.key,value:v.value,unit:v.unit,status:v.status})); return sendJson(req, res,200,{matching,differing,missingInTarget,extraInTarget}); }

if(method==='POST'&&pathname==='/report-sections/generate'){ const input = reportGenerationSchema.parse(await readBody(req)) as ReportGenerationInput & { sectionType: ReportSectionType }; const section = generateReportSection({ ...input, engineeringValues: input.engineeringValues as EngineeringValue[], sourceReferences: (input.sourceReferences ?? []) as SourceReference[], calculationResults: (input.calculationResults ?? calculationResults.filter((r)=>r.projectId===input.projectId)) as CalculationResult[] }); reportSections.create(section); return sendJson(req, res,201,section); }
if(method==='GET'&&pathname==='/report-sections'){ const projectId=searchParams.get('projectId'); return sendJson(req, res,200,projectId?reportSections.list().filter((s)=>s.projectId===projectId):reportSections.list()); }
if(method==='POST'&&pathname==='/report-sections/export-docx'){ const input = reportDocxExportSchema.parse(await readBody(req)); if(!input.projectId.trim()) return sendJson(req, res,400,{error:'projectId is required'}); if(input.reportSectionIds.length===0) return sendJson(req, res,400,{error:'At least one report section must be selected'}); const project = projects.getById(input.projectId); if(!project) return sendJson(req, res,404,{error:'Project not found'}); const selectedSections: ReportSection[] = []; for (const sectionId of input.reportSectionIds) { const section = reportSections.getById(sectionId); if(!section || section.projectId!==input.projectId) return sendJson(req, res,400,{error:'One or more selected report sections do not belong to the project'}); selectedSections.push(section); } const buffer = await exportReportSectionsToDocx({ projectId: input.projectId, projectName: project.name, selectedSections, documentTitle: input.documentTitle, generatedBy: input.generatedBy, generatedAt: input.generatedAt, includeSourceReferences: input.includeSourceReferences }); res.statusCode=200; res.setHeader('content-type','application/vnd.openxmlformats-officedocument.wordprocessingml.document'); res.setHeader('content-disposition',`attachment; filename=\"${path.basename((input.documentTitle?.trim() || `${project.name}-report-sections`).replace(/\\s+/g,'-'))}.docx\"`); return res.end(buffer); }
if(pathname.startsWith('/report-sections/')){ const id=pathname.split('/')[2]; const existing=id?reportSections.getById(id):undefined; if(!existing) return sendJson(req, res,404,{error:'Report section not found'}); if(method==='GET') return sendJson(req, res,200,existing); if(method==='PATCH'){ const updates = reportSectionUpdateSchema.parse(await readBody(req)); const updated = { ...existing, ...updates, updatedAt: new Date().toISOString() } as ReportSection; reportSections.update(id, updated); return sendJson(req, res,200,updated); } if(method==='DELETE'){ reportSections.delete(id); return sendJson(req, res,200,{deleted:true}); }}
return sendJson(req, res,404,{error:'Not found'});
} catch(error){ if(error instanceof ZodError) return sendJson(req, res,400,{error:'Validation failed',details:error.issues}); if(error instanceof Error) return sendJson(req, res,400,{error:error.message}); return sendJson(req, res,500,{error:'Unknown error'}); }}; }
export function startApiServer(port=3001){ const server=createServer(createApiHandler()); server.listen(port); return server; }
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href){ startApiServer(); }
