import test from 'node:test';
import assert from 'node:assert/strict';
import { unlink } from 'node:fs/promises';
import path from 'node:path';
import { startApiServer } from '../dist/src/index.js';

async function withServer(fn) { const server = startApiServer(0); await new Promise((r) => server.once('listening', r)); const { port } = server.address(); const baseUrl = `http://127.0.0.1:${port}`; try { await fn(baseUrl); } finally { server.close(); } }
async function createProject(base) { return (await (await fetch(`${base}/projects`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Project A', projectType: 'custom' }) })).json()); }
async function uploadDoc(base, projectId) { return (await (await fetch(`${base}/projects/${projectId}/documents`, { method: 'POST', body: new Uint8Array([1,2,3]), headers: { 'content-type': 'application/pdf', 'x-document-type': 'datasheet', 'x-filename': 'spec.pdf' } })).json()); }

test('extraction endpoint uses configured mock service and saves needs_review candidate', async () => { await withServer(async (base) => { const project = await createProject(base); const doc = await uploadDoc(base, project.id); const res = await fetch(`${base}/extractions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: project.id, documentId: doc.id }) }); assert.equal(res.status, 200); const values = await (await fetch(`${base}/engineering-values?projectId=${project.id}`)).json(); assert.ok(values.some((v) => v.status === 'needs_review' || v.status === 'ai_extracted')); }); });

test('extraction does not overwrite approved values', async () => { await withServer(async (base) => { const project = await createProject(base); const doc = await uploadDoc(base, project.id); await fetch(`${base}/engineering-values`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: project.id, key: 'nominal_pressure', label: 'Nominal Pressure', value: 205, valueType: 'number', status: 'approved', sourceReferences: [] }) }); await fetch(`${base}/extractions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: project.id, documentId: doc.id }) }); const values = await (await fetch(`${base}/engineering-values?projectId=${project.id}`)).json(); assert.equal(values.filter((v) => v.key === 'nominal_pressure' && v.status === 'approved').length, 1); }); });

test('extraction missing document returns 404', async () => { await withServer(async (base) => { const project = await createProject(base); const res = await fetch(`${base}/extractions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: project.id, documentId: 'missing' }) }); assert.equal(res.status, 404); }); });

test('extraction missing file returns clear error', async () => { await withServer(async (base) => { const project = await createProject(base); const doc = await uploadDoc(base, project.id); await unlink(path.resolve(process.cwd(), 'storage/uploads', doc.storedFilename)); const res = await fetch(`${base}/extractions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: project.id, documentId: doc.id }) }); assert.equal(res.status, 400); const body = await res.json(); assert.match(body.error, /missing on disk/); }); });
